use std::str::FromStr;

pub enum MimeType {
    AAC,
    ABW,
    APNG,
    ARC,
    AVIF,
    AVI,
    AZW,
    BIN,
    BMP,
    BZ,
    BZ2,
    CDA,
    CSH,
    CSS,
    CSV,
    DOC,
    DOCX,
    EOT,
    EPUB,
    GZ,
    GIF,
    HTM,
    ICO,
    ICS,
    JAR,
    JPEG,
    JS,
    JSON,
    JSONLD,
    MID,
    MJS,
    MP3,
    MP4,
    MPEG,
    MPKG,
    ODP,
    ODS,
    ODT,
    // Could be Opus-encoded
    OGA,
    OGV,
    OGX,
    OTF,
    PNG,
    PDF,
    PHP,
    PPT,
    PPTX,
    RAR,
    RTF,
    SH,
    SVG,
    TAR,
    TIF,
    TS,
    TTF,
    TXT,
    VSD,
    WAV,
    WEBA,
    WEBM,
    WEBP,
    WOFF,
    WOFF2,
    XHTML,
    XLS,
    XLSX,
    XML,
    XUL,
    ZIP,
    _3GP,
    _3G2,
    _7Z,
}

impl FromStr for MimeType {
    type Err = &'static str;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "audio/aac" => Ok(MimeType::AAC),
            "application/x-abiword" => Ok(MimeType::ABW),
            "image/apng" => Ok(MimeType::APNG),
            "application/x-freearc" => Ok(MimeType::ARC),
            "image/avif" => Ok(MimeType::AVIF),
            "video/x-msvideo" => Ok(MimeType::AVI),
            "application/vnd.amazon.ebook" => Ok(MimeType::AZW),
            "application/octet-stream" => Ok(MimeType::BIN),
            "image/bmp" => Ok(MimeType::BMP),
            "application/x-bzip" => Ok(MimeType::BZ),
            "application/x-bzip2" => Ok(MimeType::BZ2),
            "application/x-cdf" => Ok(MimeType::CDA),
            "application/x-csh" => Ok(MimeType::CSH),
            "text/css" => Ok(MimeType::CSS),
            "text/csv" => Ok(MimeType::CSV),
            "application/msword" => Ok(MimeType::DOC),
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document" => {
                Ok(MimeType::DOCX)
            }
            "application/vnd.ms-fontobject" => Ok(MimeType::EOT),
            "application/epub+zip" => Ok(MimeType::EPUB),
            "application/gzip" | ".gz" | "application/x-gzip" => Ok(MimeType::GZ),
            "image/gif" => Ok(MimeType::GIF),
            "text/html" => Ok(MimeType::HTM),
            "image/vnd.microsoft.icon" => Ok(MimeType::ICO),
            "text/calendar" => Ok(MimeType::ICS),
            "application/java-archive" => Ok(MimeType::JAR),
            "image/jpeg" => Ok(MimeType::JPEG),
            "text/javascript" => Ok(MimeType::JS),
            "application/json" => Ok(MimeType::JSON),
            "application/ld+json" => Ok(MimeType::JSONLD),
            "audio/midi" | "audio/x-midi" => Ok(MimeType::MID),
            "audio/mpeg" => Ok(MimeType::MP3),
            "video/mp4" => Ok(MimeType::MP4),
            "video/mpeg" => Ok(MimeType::MPEG),
            "application/vnd.apple.installer+xml" => Ok(MimeType::MPKG),
            "application/vnd.oasis.opendocument.presentation" => Ok(MimeType::ODP),
            "application/vnd.oasis.opendocument.spreadsheet" => Ok(MimeType::ODS),
            "application/vnd.oasis.opendocument.text" => Ok(MimeType::ODT),
            "audio/ogg" => Ok(MimeType::OGA),
            "video/ogg" => Ok(MimeType::OGV),
            "application/ogg" => Ok(MimeType::OGX),
            "font/otf" => Ok(MimeType::OTF),
            "image/png" => Ok(MimeType::PNG),
            "application/pdf" => Ok(MimeType::PDF),
            "application/x-httpd-php" => Ok(MimeType::PHP),
            "application/vnd.ms-powerpoint" => Ok(MimeType::PPT),
            "application/vnd.openxmlformats-officedocument.presentationml.presentation" => {
                Ok(MimeType::PPTX)
            }
            "application/vnd.rar" => Ok(MimeType::RAR),
            "application/rtf" => Ok(MimeType::RTF),
            "application/x-sh" => Ok(MimeType::SH),
            "image/svg+xml" => Ok(MimeType::SVG),
            "application/x-tar" => Ok(MimeType::TAR),
            "image/tiff" => Ok(MimeType::TIF),
            "video/mp2t" => Ok(MimeType::TS),
            "font/ttf" => Ok(MimeType::TTF),
            "text/plain" => Ok(MimeType::TXT),
            "application/vnd.visio" => Ok(MimeType::VSD),
            "audio/wav" => Ok(MimeType::WAV),
            "audio/webm" => Ok(MimeType::WEBA),
            "video/webm" => Ok(MimeType::WEBM),
            "image/webp" => Ok(MimeType::WEBP),
            "font/woff" => Ok(MimeType::WOFF),
            "font/woff2" => Ok(MimeType::WOFF2),
            "application/xhtml+xml" => Ok(MimeType::XHTML),
            "application/vnd.ms-excel" => Ok(MimeType::XLS),
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" => {
                Ok(MimeType::XLSX)
            }
            "application/xml" | "text/xml" | ".xml" | "application/atom+xml" => Ok(MimeType::XML),
            "application/vnd.mozilla.xul+xml" => Ok(MimeType::XUL),
            "application/zip" | ".zip" | "application/x-zip-compressed" => Ok(MimeType::ZIP),
            "video/3gpp" | "audio/3gpp" => Ok(MimeType::_3GP),
            "video/3gpp2" | "audio/3gpp2" => Ok(MimeType::_3G2),
            "application/x-7z-compressed" => Ok(MimeType::_7Z),
            _ => Err("Not a valid MIME type"),
        }
    }
}
